[package]
name = "combinefiles"
description = "combine files with one or many threads"
repository = "https://github.com/Trevrosa/combinefiles"
keywords = ["combine", "sparse", "file", "multithreaded"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"
version = "0.2.4"
edition = "2024"

[features]
tracing = ["dep:tracing"]
# progress = ["dep:indicatif"]
cli = ["tracing", "dep:tracing-subscriber", "dep:clap"]

[dependencies]
crossbeam-channel = "0.5.17"
tracing = { version = "0.1.44", optional = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"], optional = true }
# indicatif = { version = "0.18.6", optional = true }
clap = { version = "4.6.7", optional = true, features = ["derive"] }

[[bin]]
name = "combine"
path = "src/bin/cli.rs"
required-features = ["cli"]
